# Generated by Django 2.2.5 on 2019-09-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencyname', models.CharField(max_length=200)),
                ('registration_no', models.IntegerField()),
                ('agency_logo', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('agency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agency.Agency')),
            ],
        ),
    ]
