# Generated by Django 2.2.5 on 2019-09-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['agencyname']},
        ),
    ]
